"""Generate the app's Vital mapping from the reviewed exercise-ID manifest."""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
mapping = json.loads((Path(__file__).parent / "mapping.json").read_text())
assert mapping["schemaVersion"] == 1
assert mapping["provider"] == "vital_animations"
catalog = json.loads((ROOT / "tool/exercise_forms/catalog.json").read_text())
exercise_ids = {item["exerciseId"] for item in catalog["exercises"]}
seen_exercises = set()
asset_owners = {}
rows = []
for item in mapping["mappings"]:
    exercise_id = item["exerciseId"]
    asset_id = item["providerAssetId"]
    assert exercise_id in exercise_ids and exercise_id not in seen_exercises
    if asset_id in asset_owners:
        assert item.get("sharedWith") == asset_owners[asset_id], (
            f"Undocumented shared Vital video: {asset_id}"
        )
    else:
        asset_owners[asset_id] = exercise_id
    assert item["sourceAsset"].endswith(f"/{asset_id}.mp4")
    seen_exercises.add(exercise_id)
    rows.append(
        f"  '{exercise_id}': ExerciseMedia(\n"
        f"    exerciseId: '{exercise_id}',\n"
        "    provider: 'vital_animations',\n"
        f"    providerAssetId: '{asset_id}',\n"
        "    mediaType: 'video',\n"
        f"    assetPath: 'assets/vital_videos/{asset_id}.mp4',\n"
        f"    thumbnailAssetPath: 'assets/vital_thumbnails/{asset_id}.png',\n"
        "  ),"
    )
assert all(item["exerciseId"] not in seen_exercises for item in mapping["reviewRequired"])
text = "// GENERATED by tool/vital_media/generate_catalog.py. Edit mapping.json.\n"
text += "part of 'exercise_media.dart';\n\n"
text += "const Map<String, ExerciseMedia> _vitalMedia = {\n"
text += "\n".join(rows) + "\n};\n"
(ROOT / "lib/vital_media_catalog.g.dart").write_text(text)
print(f"Generated {len(rows)} Vital mappings; {len(mapping['reviewRequired'])} require review")
