"""Generate the synchronous Flutter catalog from the authoring source of truth."""
import argparse, copy, json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]
source = json.loads((Path(__file__).parent / 'catalog.json').read_text())
assert source['schemaVersion'] == 1
parser = argparse.ArgumentParser()
parser.add_argument('--review-candidates', default='', help='Temporary QA catalog; restore with a normal generation after testing')
args = parser.parse_args()
candidates = set(filter(None, args.review_candidates.split(',')))
ids = set()
for item in source['exercises']:
    assert item['exerciseId'] not in ids
    ids.add(item['exerciseId'])
    assert item['exerciseId'] and isinstance(item['exerciseName'], str)
    assert len(item['aliases']) == len(set(item['aliases']))
    assert item['recordType'] in ['weightReps', 'assistedReps', 'bodyweightReps', 'timed', 'cardio', 'distance', 'loadedDistance']
    assert item['equipmentLabel'] and isinstance(item['tags'], list)
    assert item.get('distanceUnit', 'km') in ['m', 'km']
    if item['status'] == 'planned':
        assert item['assetPath'] is None
    assert 0 < item['animationSpeed'] <= 2
    assert 0 < item['rangeOfMotion'] <= 1
    assert item['status'] in ['planned', 'authored', 'verified']
    assert isinstance(item.get('previewEnabled', False), bool)
    if item.get('previewEnabled', False):
        assert item['status'] == 'authored', f'Preview must remain authored: {item["exerciseId"]}'
        assert item['assetPath'] and (ROOT / item['assetPath']).is_file()
        assert item.get('review', {}).get('staticPose') is True, f'Preview pose unchecked: {item["exerciseId"]}'
    if item['status'] == 'verified':
        assert item['assetPath'] and (ROOT / item['assetPath']).is_file()
        if item['exerciseId'] not in {'bench_press', 'incline_dumbbell_press'}:
            assert item.get('references'), f'Missing reference: {item["exerciseId"]}'
            for check in ('equipmentReference', 'staticPose', 'motion', 'android', 'ios', 'productionRoute'):
                assert item.get('review', {}).get(check) is True, f'Unreviewed {check}: {item["exerciseId"]}'
assert candidates <= ids, f'Unknown QA candidates: {candidates - ids}'
by_id = {item['exerciseId']: item for item in source['exercises']}
for item in source['exercises']:
    assert isinstance(item.get('selectable', True), bool)
    canonical = item.get('canonicalExerciseId')
    if canonical is not None:
        assert canonical in ids and canonical != item['exerciseId']
        target = by_id[canonical]
        assert 'canonicalExerciseId' not in target, 'Compatibility must resolve in one step'
        assert item.get('selectable') is False and target.get('selectable', True)
        for field in ('recordType', 'loadMode', 'distanceUnit'):
            assert item.get(field) == target.get(field), f'Incompatible {field}: {item["exerciseId"]}'
output = copy.deepcopy(source['exercises'])
for item in output:
    if item['exerciseId'] in candidates:
        assert item['status'] == 'authored' and item['assetPath']
        for check in ('equipmentReference', 'staticPose', 'motion', 'android', 'ios'):
            assert item.get('review', {}).get(check) is True, f'Unreviewed candidate {check}: {item["exerciseId"]}'
        item['status'] = 'verified'
text = '// GENERATED by tool/exercise_forms/generate_catalog.py. Edit catalog.json.\n'
if candidates:
    text += '// TEMPORARY QA CANDIDATES: ' + ','.join(sorted(candidates)) + '. Regenerate before release.\n'
text += 'const List<Map<String, Object?>> exerciseFormData = '
text += json.dumps(output, ensure_ascii=False, indent=2) + ';\n'
(ROOT / 'lib/exercise_form_catalog.g.dart').write_text(text)
print(f'Generated {len(ids)} definitions')
